# Generated by Django 4.2.3 on 2023-07-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeowner',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='storeowner',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Salesperson',
        ),
    ]
