# Generated by Django 4.2.3 on 2023-07-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_remove_storeowner_salesperson_storeowner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeowner',
            name='email',
            field=models.EmailField(max_length=20, null=True, unique=True),
        ),
    ]
